version: '3.8'
services:
 web:
  build: .
  ports:
   - "3000:3000"
  env_file:
   - ./app.env
  depends_on:
   - mongo
  volumes:
   - ./app:/app
  restart : unless-stopped
 mongo:
  image: mongo:5.0
  volumes:
   - mongo-data:/data/db
  restart: unless-stopped
 nginx:
  image: nginx:latest
  #container_name: nginx_proxy
  ports:
   - "8081:80"
  volumes:
   - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
  depends_on:
   - web
volumes:
 mongo-data:
  
  